// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVM9OkEJa_rdAID5ydC8gGKjNaU6fFzQI',
    appId: '1:1077107109427:web:bbe6268a7b4f1831717d46',
    messagingSenderId: '1077107109427',
    projectId: 'ecosystem-6b056',
    authDomain: 'ecosystem-6b056.firebaseapp.com',
    storageBucket: 'ecosystem-6b056.appspot.com',
    measurementId: 'G-64EF1WMHB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMMvY5xcBezL_0nZRohwZH_lk6OZVfzvA',
    appId: '1:1077107109427:android:55e132cb2efe75ea717d46',
    messagingSenderId: '1077107109427',
    projectId: 'ecosystem-6b056',
    storageBucket: 'ecosystem-6b056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS7sZXs2cnubG8MsOuYJcaw23r2ZMphhw',
    appId: '1:1077107109427:ios:8331a57ca93dc4e8717d46',
    messagingSenderId: '1077107109427',
    projectId: 'ecosystem-6b056',
    storageBucket: 'ecosystem-6b056.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS7sZXs2cnubG8MsOuYJcaw23r2ZMphhw',
    appId: '1:1077107109427:ios:8331a57ca93dc4e8717d46',
    messagingSenderId: '1077107109427',
    projectId: 'ecosystem-6b056',
    storageBucket: 'ecosystem-6b056.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8SAhsMJpkbxkUY2iOA7rvsmAXYlraGGs',
    appId: '1:1077107109427:web:3a7b53e403307347717d46',
    messagingSenderId: '1077107109427',
    projectId: 'ecosystem-6b056',
    authDomain: 'ecosystem-6b056.firebaseapp.com',
    storageBucket: 'ecosystem-6b056.appspot.com',
    measurementId: 'G-XKDEFCVTB2',
  );
}
